name = "Pelong81"
main = "_worker.js"
compatibility_date = "2023-05-26"
node_compat = true
workers_dev = true

[vars]
PROXYIP = "168.138.165.174"
UUID = "1d873771-2bf8-4e01-88e8-ea24af9003f8"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
